name: My GitHub Actions Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello from GithubActions"
      - name: Run Build 
        run: cd | frontend npm run build