name: My GitHub Actions Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install 
      - name: Run Build
        working-directory: ./frontend 
        run: npm run build
