name: My GitHub Actions Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - name: Hello World
        run: echo "Hello from GithubActions"
      - name: Build Frontend
        run: npm run build
        working-directory: frontend
